// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvuHoW9OvxGOaOAEHrtvESF_yd9-nItl8',
    appId: '1:227117946330:web:710a7173c3c8db4b2b1ce3',
    messagingSenderId: '227117946330',
    projectId: 'quizie-quizz',
    authDomain: 'quizie-quizz.firebaseapp.com',
    databaseURL: 'https://quizie-quizz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizie-quizz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIuDIT-qr7HVPYIE5U4QOzDQGgSULFeLs',
    appId: '1:227117946330:android:fec2656b8c28c99e2b1ce3',
    messagingSenderId: '227117946330',
    projectId: 'quizie-quizz',
    databaseURL: 'https://quizie-quizz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizie-quizz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQHUySMS2Y4I0rBCKGda53XZu4_vvt0-4',
    appId: '1:227117946330:ios:7b0a83e8dbca95e32b1ce3',
    messagingSenderId: '227117946330',
    projectId: 'quizie-quizz',
    databaseURL: 'https://quizie-quizz-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'quizie-quizz.appspot.com',
    iosBundleId: 'com.kbj.quzie',
  );
}
